name: Update Data and Trigger Vercel Deploy

on:
  schedule:
    - cron: '0 0 * * *' # 每日 UTC 时间午夜运行 (可根据需要修改)
  workflow_dispatch: # 允许从 GitHub Actions 页面手动触发

jobs:
  update_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
        id: setup-chrome

      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@v2
        with:
          # 可选：指定与Chrome匹配的ChromeDriver版本
          # chromedriver-version: '119.0.6045.105'
          # 不指定版本则会自动匹配已安装的Chrome版本
          chromedriver-version: 'latest'

      - name: Print Chrome & ChromeDriver paths
        run: |
          echo "Chrome path: $(which chrome)"
          echo "Chrome version: $(chrome --version)"
          echo "ChromeDriver path: $(which chromedriver)"
          echo "ChromeDriver version: $(chromedriver --version)"
          echo "CHROMEDRIVER_PATH=$(which chromedriver)" >> $GITHUB_ENV

      - name: Run update_qieman_data.py
        env:
          TZ: Asia/Shanghai # 设置时区，如果脚本中涉及时间操作并依赖特定时区
        run: python update_qieman_data.py

      - name: Run fetch_fund_data.py
        env:
          TZ: Asia/Shanghai # 设置时区，如果脚本中涉及时间操作并依赖特定时区
        run: python fetch_fund_data.py

      - name: Set up Node.js
        uses: actions/setup-node@v4 # Updated to v4
        with:
          node-version: '18.x' # Using a recent LTS version

      - name: Install npm dependencies
        run: npm install

      - name: Run build script
        run: npm run build
        env:
          TZ: Asia/Shanghai # If build script also involves time-sensitive operations

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated data update and build"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          file_pattern: "src/data/*.json public/data/grid/latest_netvalues.json public/data/grid/latest_netvalues.json.backup dist"
          # The 'dist' at the end will include all changes within the dist directory.
          # 此 action 默认推送到当前分支 (通常是 main/master)
          # 如果您的 Vercel 监控其他分支，请相应调整 